[versions]
kotlin = "1.8.21"
jvmToolchain = "16"
spigot = "1.17.1-R0.1-SNAPSHOT"

[libraries]
stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.+" }
spotless = { id = "com.diffplug.spotless", version = "6.+" }