[versions]
kotlin = "1.9.24"
jvmToolchain = "17"
paper = "1.20.4-R0.1-SNAPSHOT"

[libraries]
stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.+" }
spotless = { id = "com.diffplug.spotless", version = "6.+" }